# hostname (and path) to the root
baseURL: "https://keen-noether-e3b890.netlify.com"

# Customer parameters
params:
  description: "My theme"
  # rssURL:
  #   main: "https://gomakethings.com/feed/index.xml"
  # rssLimit: 7

# Caches
caches:
  getjson:
    maxAge: "5m"

# The language code for the site
languageCode: "de-de"

# Site title
title: "Musikversicherung.com"

# theme to use (located by default in /themes/THEMENAME/)
theme: "my-theme"

menu:
  main:
    - identifier: faq
      name: FAQ
      title: FAQ
      url: /faq
      weight: 10
    - identifier: kontakt
      name: Kontakt
      title: Kontakt
      url: /kontakt
      weight: 10

# Permalinks
# See "content-management/permalinks"
permalinks:
  # articles: /:title/

# Use absolute URLs
canonifyURLs: true

# Allows you to disable all page types and will render nothing related to 'kind';
# values = "page", "home", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"
disableKinds: ["RSS", "hugoGeneratorInject", "404"]

# Files to ignore while rendering
ignoreFiles: []
# the length of text to show in a .Summary
# summaryLength: 70

# Pagination
# paginate: 35
# paginatePath: "page"

# Markdown Options
# blackfriday:
#   fractions: false

# Syntax Highlighting
# pygmentsCodefences: true
# pygmentsUseClasses: true
